# Generated by Qodo Gen
import pytest

from api_client.helpers.rich_printer import get_rek_iscat_color


class TestGetRekIscatColor:

    # Returns "green" when input is "true"
    def test_returns_green_for_true(self):
        # Arrange
        rek_iscat = "true"

        # Act
        result = get_rek_iscat_color(rek_iscat)

        # Assert
        assert result == "green"

    # Returns "red" when input is "false"
    def test_returns_red_for_false(self):
        # Arrange
        rek_iscat = "false"

        # Act
        result = get_rek_iscat_color(rek_iscat)

        # Assert
        assert result == "red"

    # Returns "red" when input is "N/A"
    def test_returns_red_for_na(self):
        # Arrange
        rek_iscat = "N/A"

        # Act
        result = get_rek_iscat_color(rek_iscat)

        # Assert
        assert result == "red"

    # Handles case-insensitive comparison for "true"
    def test_case_insensitive_true(self):
        # Arrange
        rek_iscat = "TRUE"

        # Act
        result = get_rek_iscat_color(rek_iscat)

        # Assert
        assert result == "green"

    # Handles case-insensitive comparison for "false"
    def test_case_insensitive_false(self):
        # Arrange
        rek_iscat = "FALSE"

        # Act
        result = get_rek_iscat_color(rek_iscat)

        # Assert
        assert result == "red"
