# Generated by Qodo Gen
import os

import pytest


class TestGenBatchFilePath:

    # Returns correct file path with client_id and batch_id in the format "{client_id}_{batch_id}.json"
    def test_returns_correct_file_path_format(self, mocker):
        # Arrange
        client_id = "client123"
        batch_id = "batch456"
        expected_filename = f"{client_id}_{batch_id}.json"
        mock_cwd = "/fake/cwd"
        mocker.patch("os.getcwd", return_value=mock_cwd)
        mocker.patch("os.path.exists", return_value=True)
        mocker.patch("os.makedirs")

        # Act
        from api_client.helpers.general import gen_batch_file_path

        result = gen_batch_file_path(client_id, batch_id)

        # Assert
        assert os.path.basename(result) == expected_filename
        assert os.path.dirname(result) == os.path.join(mock_cwd, "logs")

    # Creates a "logs" directory in the current working directory if it doesn't exist
    def test_creates_logs_directory_if_not_exists(self, mocker):
        # Arrange
        client_id = "client123"
        batch_id = "batch456"
        mock_cwd = "/fake/cwd"
        logs_path = os.path.join(mock_cwd, "logs")

        mocker.patch("os.getcwd", return_value=mock_cwd)
        mock_exists = mocker.patch("os.path.exists", return_value=False)
        mock_makedirs = mocker.patch("os.makedirs")

        # Act
        from api_client.helpers.general import gen_batch_file_path

        gen_batch_file_path(client_id, batch_id)

        # Assert
        mock_exists.assert_called_once_with(logs_path)
        mock_makedirs.assert_called_once_with(logs_path)

    # Handles valid string inputs for both client_id and batch_id
    def test_handles_valid_string_inputs(self, mocker):
        # Arrange
        test_cases = [
            ("client123", "batch456"),
            ("client-abc", "batch-xyz"),
            ("CLIENT_123", "BATCH_456"),
            ("123", "456"),
        ]
        mocker.patch("os.getcwd", return_value="/fake/cwd")
        mocker.patch("os.path.exists", return_value=True)
        mocker.patch("os.makedirs")

        # Act & Assert
        from api_client.helpers.general import gen_batch_file_path

        for client_id, batch_id in test_cases:
            result = gen_batch_file_path(client_id, batch_id)
            assert os.path.basename(result) == f"{client_id}_{batch_id}.json"

    # Returns an absolute path that includes the current working directory
    def test_returns_absolute_path_with_cwd(self, mocker):
        # Arrange
        client_id = "client123"
        batch_id = "batch456"
        mock_cwd = "/fake/cwd"
        mocker.patch("os.getcwd", return_value=mock_cwd)
        mocker.patch("os.path.exists", return_value=True)
        mocker.patch("os.makedirs")

        # Act
        from api_client.helpers.general import gen_batch_file_path

        result = gen_batch_file_path(client_id, batch_id)

        # Assert
        assert result.startswith(mock_cwd)
        assert os.path.isabs(result)

    # Successfully joins path components using os.path.join
    def test_joins_path_components_correctly(self, mocker):
        # Arrange
        client_id = "client123"
        batch_id = "batch456"
        mock_cwd = "/fake/cwd"
        expected_logs_dir = os.path.join(mock_cwd, "logs")
        expected_file_path = os.path.join(
            expected_logs_dir, f"{client_id}_{batch_id}.json"
        )

        mocker.patch("os.getcwd", return_value=mock_cwd)
        mocker.patch("os.path.exists", return_value=True)
        mocker.patch("os.makedirs")

        # Act
        from api_client.helpers.general import gen_batch_file_path

        result = gen_batch_file_path(client_id, batch_id)

        # Assert
        assert result == expected_file_path

    # Handles empty strings for client_id or batch_id
    def test_handles_empty_string_inputs(self, mocker):
        # Arrange
        test_cases = [("", "batch456"), ("client123", ""), ("", "")]
        mock_cwd = "/fake/cwd"
        mocker.patch("os.getcwd", return_value=mock_cwd)
        mocker.patch("os.path.exists", return_value=True)
        mocker.patch("os.makedirs")

        # Act & Assert
        from api_client.helpers.general import gen_batch_file_path

        for client_id, batch_id in test_cases:
            result = gen_batch_file_path(client_id, batch_id)
            assert os.path.basename(result) == f"{client_id}_{batch_id}.json"
            assert os.path.dirname(result) == os.path.join(mock_cwd, "logs")

    # Handles very long client_id or batch_id values
    def test_handles_very_long_ids(self, mocker):
        # Arrange
        long_client_id = "client" + "x" * 1000
        long_batch_id = "batch" + "y" * 1000
        mock_cwd = "/fake/cwd"
        mocker.patch("os.getcwd", return_value=mock_cwd)
        mocker.patch("os.path.exists", return_value=True)
        mocker.patch("os.makedirs")

        # Act
        from api_client.helpers.general import gen_batch_file_path

        result = gen_batch_file_path(long_client_id, long_batch_id)

        # Assert
        assert os.path.basename(result) == f"{long_client_id}_{long_batch_id}.json"
        assert os.path.dirname(result) == os.path.join(mock_cwd, "logs")

    # Behavior when logs directory exists but is not writable
    def test_logs_directory_not_writable(self, mocker):
        # Arrange
        client_id = "client123"
        batch_id = "batch456"
        mock_cwd = "/fake/cwd"
        logs_path = os.path.join(mock_cwd, "logs")

        mocker.patch("os.getcwd", return_value=mock_cwd)
        mocker.patch("os.path.exists", return_value=True)  # Directory exists
        mock_makedirs = mocker.patch(
            "os.makedirs", side_effect=PermissionError("Permission denied")
        )

        # Act & Assert
        from api_client.helpers.general import gen_batch_file_path

        # The function should still return the path even if the directory can't be created
        result = gen_batch_file_path(client_id, batch_id)

        # The function should still return the correct path
        assert result == os.path.join(logs_path, f"{client_id}_{batch_id}.json")
        # makedirs should not be called since the directory exists
        mock_makedirs.assert_not_called()
